services:
  db_test:
    container_name: db
    image: postgres:latest
    env_file:
      - .env_test
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    command: postgres
    ports:
      - "5431:5432"
    restart: unless-stopped

  backend_test:
    depends_on:
      - db_test
    links:
      - db_test
    container_name: backend_test
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["sh", "docker-entrypoint.sh"]
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ENV="TEST"
    volumes:
      - .:/app
    ports:
      - "8081:8080"

volumes:
  postgres_data_test:
