services:
  db:
    container_name: db
    image: postgres:latest
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    command: postgres
    ports:
      - "5432:5432"
    restart: unless-stopped

  backend:
    depends_on:
      - db
    links:
      - db
    container_name: backend
    image: backend
    build:
      context: .
      dockerfile: Dockerfile
    entrypoint: ["sh", "docker-entrypoint.sh"]
    restart: unless-stopped
    env_file:
      - .env
    volumes:
      - .:/app:delegated
    ports:
      - "8080:8080"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8080/docs"]
      interval: 10s
      timeout: 10s
      retries: 3


volumes:
  postgres_data:
