"""add receipt model

Revision ID: 3ce1c0227e9e
Revises: 5e50f76d9599
Create Date: 2025-01-13 17:32:22.140452

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '3ce1c0227e9e'
down_revision: Union[str, None] = '5e50f76d9599'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('receipts',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('total_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('payment_type', sa.Enum('CASH', 'CASHLESS', name='paymenttype'), nullable=False),
    sa.Column('payment_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('rest_amount', sa.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('products', sa.JSON(), nullable=False),
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('created', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_created'), 'receipts', ['created'], unique=False)
    op.drop_index('ix_user_created', table_name='users')
    op.drop_index('ix_user_email', table_name='users')
    op.create_index(op.f('ix_users_created'), 'users', ['created'], unique=False)
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_index(op.f('ix_users_created'), table_name='users')
    op.create_index('ix_user_email', 'users', ['email'], unique=True)
    op.create_index('ix_user_created', 'users', ['created'], unique=False)
    op.drop_index(op.f('ix_receipts_created'), table_name='receipts')
    op.drop_table('receipts')
    # ### end Alembic commands ###
