"""add public_id for receipt

Revision ID: d395cdf1be43
Revises: 3ce1c0227e9e
Create Date: 2025-01-14 15:37:54.873277

"""
from typing import Sequence, Union

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = 'd395cdf1be43'
down_revision: Union[str, None] = '3ce1c0227e9e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('receipts', sa.Column('public_id', sa.String(length=36), nullable=True))
    op.create_unique_constraint(None, 'receipts', ['public_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'receipts', type_='unique')
    op.drop_column('receipts', 'public_id')
    # ### end Alembic commands ###
